# Copyright (c) 2024 Espresso Systems (espressosys.com)
# This file is part of the HotShot Builder Protocol.
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


[meta]
NAME = "hs-builder-submit"
DESCRIPTION = ""
FORMAT_VERSION = "0.1.0"

[route.submit_txn]
PATH = ["/submit"]
METHOD = "POST"
DOC = """
Submit a transaction to builder's private mempool."

Returns transaction hash
"""

[route.submit_batch]
PATH = ["/batch"]
METHOD = "POST"
DOC = """
Submit a list of transactions to builder's private mempool."

Returns the corresponding list of transaction hashes
"""
