rounds = 100
transactions_per_round = 10
node_index = 0
padding = 10
start_delay_seconds = 60

[libp2p_config]
bootstrap_mesh_n_high = 4
bootstrap_mesh_n_low = 4
bootstrap_mesh_outbound_min = 2
bootstrap_mesh_n = 4
mesh_n_high = 4
mesh_n_low = 4
mesh_outbound_min = 2
mesh_n = 4
next_view_timeout = 10
propose_min_round_time = 0
propose_max_round_time = 10
online_time = 10
num_txn_per_round = 10
base_port = 9000

[config]
total_nodes = 10
max_transactions = 100
min_transactions = 0
next_view_timeout = 10000
timeout_ratio = [11, 10]
round_start_delay = 1
start_delay = 1
num_bootstrap = 5

[config.propose_min_round_time]
secs = 0
nanos = 0

[config.propose_max_round_time]
secs = 1
nanos = 0
