[package]
name = "hotshot-testing"
version = "0.1.0"
edition = "2021"
description = "Types and traits for the HotShot consesus module"
authors = ["Victor Koenders <vkoenders@espressosys.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["async-std-executor"]
full-ci = ["async-std-executor", "slow-tests"]
slow-tests = []
async-std-executor = ["dep:async-std", "hotshot/async-std-executor", "hotshot-consensus/async-std-executor", "hotshot-types/async-std-executor", "hotshot-utils/async-std-executor"]
tokio-executor = ["dep:tokio", "hotshot/tokio-executor", "hotshot-consensus/tokio-executor", "hotshot-types/tokio-executor", "hotshot-utils/tokio-executor"]

[dependencies]
async-std = { version = "1.12.0", optional = true }
async-trait = "0.1.57"
cfg-if = "1"
commit = { git = "https://github.com/EspressoSystems/commit", tag = "0.1.0" }
either = { version = "1.8.0" }
futures = "0.3.24"
hotshot = { path = "../", features = ["hotshot-testing"] }
hotshot-consensus = { path = "../consensus" }
hotshot-types = { path = "../types" }
hotshot-utils = { path = "../utils", features = ["logging-utils"] }
rand = "0.8.5"
snafu = { version = "0.7.0", features = ["backtraces"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"], optional = true }
tracing = "0.1.36"

[dev-dependencies]
proptest = "1.0.0"
tempfile = "3.3.0"

