[package]
name = "hotshot-consensus"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
custom_debug = "0.5"
futures = "0.3.23"
hotshot-types = { path = "../types" }
snafu = "0.7.0"
async-std = "1.12.0"
tracing = "0.1.36"
flume = "0.10.14"
hotshot-utils = { path = "../utils", features = ["logging-utils"] }
commit = { git = "https://github.com/EspressoSystems/commit", tag = "0.1.0" }
