[package]
name = "hotshot-consensus"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
full-ci = ["async-std-executor"]
tokio-ci = ["tokio-executor"]
async-std-executor = [
    "dep:async-std",
    "hotshot-types/async-std-executor",
    "async-compatibility-layer/async-std-executor",
]
tokio-executor = [
    "dep:tokio",
    "hotshot-types/tokio-executor",
    "async-compatibility-layer/tokio-executor",
]
profiling = ["async-compatibility-layer/profiling"]
channel-flume = ["hotshot-types/channel-flume", "async-compatibility-layer/channel-flume"]
channel-tokio = ["hotshot-types/channel-tokio", "async-compatibility-layer/channel-tokio"]
channel-async-std = [
    "hotshot-types/channel-async-std",
    "async-compatibility-layer/channel-async-std",
]

[dependencies]
async-compatibility-layer = { git = "https://github.com/EspressoSystems/HotShot.git", tag = "1.0.1" , default-features = false, features = [ "logging-utils" ] }
async-lock = "2.6"
async-std = { version = "1.12", optional = true }
async-trait = "0.1.58"
# TODO ed: Delete this dependency after https://github.com/EspressoSystems/HotShot/issues/614 is finished
bincode = "1.3.3"
commit = { git = "https://github.com/EspressoSystems/commit", tag = "0.2.2" }
custom_debug = "0.5"
futures = "0.3.25"
hotshot-types = { path = "../types", default-features = false }
hotshot-utils = { path = "../utils"}
snafu = "0.7.3"
tokio = { version = "1", optional = true, features = [
    "fs",
    "io-util",
    "io-std",
    "macros",
    "net",
    "parking_lot",
    "process",
    "rt",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
    "tracing",
] }
tracing = "0.1.37"
time = "0.3.17"
