rounds = 100
transactions_per_round = 10
transaction_size = 1000
node_index = 0
seed = [
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
start_delay_seconds = 0
cdn_marshal_address = "127.0.0.1:9000"

[config]
num_nodes_with_stake = 100
num_nodes_without_stake = 0
staked_committee_nodes = 100
non_staked_committee_nodes = 0
max_transactions = 1
min_transactions = 1
next_view_timeout = 30000
timeout_ratio = [
    11,
    10,
]
round_start_delay = 1000
start_delay = 1
num_bootstrap = 5

[libp2p_config]
index_ports = true
bootstrap_mesh_n_high = 4
bootstrap_mesh_n_low = 4
bootstrap_mesh_outbound_min = 2
bootstrap_mesh_n = 4
mesh_n_high = 4
mesh_n_low = 4
mesh_outbound_min = 2
mesh_n = 4
online_time = 10
base_port = 9000

[web_server_config]
url = "http://localhost:9000"

[da_web_server_config]
url = "http://localhost:9001"


[web_server_config.wait_between_polls]
secs = 0
nanos = 100000000 # 10 ms

[da_web_server_config.wait_between_polls]
secs = 0
nanos = 100000000 # 10 ms

[config.propose_min_round_time]
secs = 0
nanos = 0

# TODO (Keyao) Clean up configuration parameters.
# <https://github.com/EspressoSystems/HotShot/issues/1823>
[config.propose_max_round_time]
secs = 2
nanos = 0
